### ISSUE TITLE
DFPlayerSoundPlayer doesn't work

### ISSUE THREAD

**Issue by carloslancha** [JakeS0ft/USaber#3]
Hi again!

I've been trying to make DFPlayer work with no luck. Everything is wired correctly (in fact, if I use DIYuniSoundPlayer it works, more or less), the program compiles (DFPlayer_SoundTest example) and runs, all the message are shown through the monitor but nothing sounds.

Any idea? Has it ever worked?

Thanks!

**Comment by JakeS0ft** [comment]
That was a one-off that I wrote to work with a particular module that has built in flash. For whatever reason, it doesn't seem to work with the modules with SD cards or with the DIYino FX boards. 

It worked on my breadboard with that one specific module, but never in a saber. This is why it is disabled in the build by default. 

If you are using an SD card, the DIYinoSoundPlayer is what you should use.
